sk.transit.api.key: ${TRANSIT_API_KEY}
myData.base.path.subway: src/main/resources/data/subway/
kakao.api.key: ${KAKAO_API_KEY}
openData.api.key: ${OPEN_DATA_API_KEY}
naver.api.id: ${NAVER_API_ID}
naver.api.secret: ${NAVER_API_SECRET}


spring:
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/HomeFinder
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  batch:
    job:
      names: ${job.name:NONE}
    jdbc:
      initialize-schema: always
  data:
    redis:
      url: ${REDIS_URL} # Heroku CLI 에서 가져온 REDIS_URL 값 주입 (Heroku 사이트 X)

