sk.transit.api.key: ${TRANSIT_API_KEY}
myData.base.path.subway: src/main/resources/data/subway/

spring:
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/HomeFinder
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

